// AUTO-GENERATED by scripts/generate-finanzamt-accounts.mjs – do not edit by hand.
// Source: BMF "Steuerzahlungen" (bmf.gv.at), 36 official Finanzamt accounts.
import { normalizeIban } from './iban'

export interface FinanzamtAccount {
  /** Dienststellen number – also the first two digits of tax numbers it manages. */
  office: string
  name: string
  iban: string
}

export const FINANZAMT_ACCOUNTS: FinanzamtAccount[] = [
  { office: "11", name: "Finanzamt für Großbetriebe", iban: "AT880100000005504116" },
  { office: "37", name: "Amt für Betrugsbekämpfung", iban: "AT090100000005504374" },
  { office: "03", name: "Dienststelle Wien 3/6/7/11/15 Schwechat Gerasdorf", iban: "AT870100000005504037" },
  { office: "06", name: "Dienststelle Wien 8/16/17", iban: "AT260100000005504068" },
  { office: "07", name: "Dienststelle Wien 4/5/9/10/18/19 Klosterneuburg", iban: "AT310100000005504075" },
  { office: "08", name: "Dienststelle Wien 12/13/14 Purkersdorf", iban: "AT360100000005504082" },
  { office: "09", name: "Dienststelle Wien 1/23", iban: "AT620100000005504099" },
  { office: "10", name: "Dienststelle Sonderzuständigkeiten: für Private, Unternehmen und Behörden hinsichtlich der Rechtsgeschäftsgebühren hinsichtlich der Eingaben beim Bundesverwaltungsgericht, beim Bundesfinanzgericht und bei den Landesverwaltungsgerichten", iban: "AT830100000005504109" },
  { office: "10", name: "Dienststelle Sonderzuständigkeiten: ausschließlich für Behörden hinsichtlich der festen Gebühren", iban: "AT560100000005804713" },
  { office: "12", name: "Dienststelle Wien 2/20/21/22", iban: "AT930100000005504123" },
  { office: "15", name: "Dienststelle Amstetten Melk Scheibbs", iban: "AT320100000005504154" },
  { office: "16", name: "Dienststelle Baden Mödling", iban: "AT370100000005504161" },
  { office: "22", name: "Dienststelle Weinviertel", iban: "AT280100000005504226" },
  { office: "23", name: "Dienststelle Waldviertel", iban: "AT330100000005504233" },
  { office: "29", name: "Dienststelle Niederösterreich Mitte", iban: "AT080100000005504295" },
  { office: "38", name: "Dienststelle Bruck Eisenstadt Oberwart", iban: "AT140100000005504381" },
  { office: "41", name: "Dienststelle Braunau Ried Schärding", iban: "AT540100000005524419" },
  { office: "46", name: "Dienststelle Linz", iban: "AT030100000005524464" },
  { office: "51", name: "Dienststelle Kirchdorf Perg Steyr", iban: "AT650100000005524512" },
  { office: "52", name: "Dienststelle Freistadt Rohrbach Urfahr", iban: "AT910100000005524529" },
  { office: "53", name: "Dienststelle Gmunden Vöcklabruck", iban: "AT960100000005524536" },
  { office: "54", name: "Dienststelle Grieskirchen Wels", iban: "AT040100000005524543" },
  { office: "57", name: "Dienststelle Klagenfurt St. Veit Wolfsberg", iban: "AT920100000005564572" },
  { office: "61", name: "Dienststelle Spittal Villach", iban: "AT520100000005564613" },
  { office: "67", name: "Dienststelle Oststeiermark", iban: "AT070100000005534674" },
  { office: "68", name: "Dienststelle Graz-Stadt", iban: "AT120100000005534681" },
  { office: "69", name: "Dienststelle Steiermark Mitte", iban: "AT380100000005534698" },
  { office: "71", name: "Dienststelle Judenburg Liezen", iban: "AT640100000005534715" },
  { office: "72", name: "Dienststelle Deutschlandsberg Leibnitz Voitsberg", iban: "AT690100000005534722" },
  { office: "81", name: "Dienststelle Innsbruck", iban: "AT310100000005544815" },
  { office: "83", name: "Dienststelle Tirol Ost", iban: "AT620100000005544839" },
  { office: "84", name: "Dienststelle Landeck Reutte", iban: "AT670100000005544846" },
  { office: "90", name: "Dienststelle St. Johann Tamsweg Zell am See", iban: "AT900100000005554908" },
  { office: "91", name: "Dienststelle Salzburg-Stadt", iban: "AT950100000005554915" },
  { office: "93", name: "Dienststelle Salzburg-Land", iban: "AT290100000005554939" },
  { office: "98", name: "Dienststelle Vorarlberg", iban: "AT630100000005574988" },
]

const BY_IBAN = new Map(FINANZAMT_ACCOUNTS.map((a) => [a.iban, a]))

/** Offline "Verification of Payee" against the official BMF directory. */
export function findFinanzamtAccount(iban: string): FinanzamtAccount | undefined {
  return BY_IBAN.get(normalizeIban(iban))
}

/** "08 345/6789" or "123456789 2604+…" → Dienststellen number "08". */
export function officeFromRemittance(remittance: string): string | undefined {
  const m = /(?:StNr\.?:?\s*|^\s*)(\d{2})[\s-]?\d{3}\/?\d{4}\b/.exec(remittance)
  return m?.[1]
}
